### ISSUE TITLE
Disconnect at boot or at random

### ISSUE THREAD

**Issue by TomZegers** [ksya/ha-nefiteasy#15]
I am still experiencing unexpected disconnects while booting or while online.
The new code is uploaded.

I get the following error messages:
Unexpected disconnect of xxxxxxx with Bosch server
and:
The following integrations and platforms could not be set up:

nefiteasy
Please check your config.

**Comment by sanderlv** [comment]
yes, me too...

have commented here as well:
https://community.home-assistant.io/t/nefit-easy-client/8148/270

**Comment by RubenDijk** [comment]
Same here
![image](https://user-images.githubusercontent.com/18540436/76350514-33522400-630c-11ea-8f58-b9b1396c33d5.png)

When reboot it dont start. sometimes you need to reboot a several times and it works again

**Comment by liquid-motion** [comment]
Same here. Since the latest update I have to keep on rebooting. Even when increasing the timeout.

**Comment by Step-han** [comment]
Same issue here...

**Comment by RubenDijk** [comment]
So far, I can't get him to work at all :(

2020-04-03 21:22:00 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 826, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 406, in data_received
    self._spawn_event(xml)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 970, in _spawn_event
    stanza = self._build_stanza(xml)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 951, in _build_stanza
    stanza = stanza_type(self, xml)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 1390, in __init__
    ElementBase.__init__(self, xml, parent)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 416, in __init__
    if self.setup(xml):
  File "/usr/local/lib/python3.7/site-packages/slixmpp/stanza/stream_features.py", line 27, in setup
    self.values = self.values
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 615, in _set_stanza_values
    self[full_interface] = value
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 753, in __setitem__
    lang=lang)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 959, in _set_sub_text
    return self._del_sub(name, lang=lang)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 1040, in _del_sub
    parent = self.xml.find(parent_path)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 299, in find
    return ElementPath.find(self, path, namespaces)
  File "/usr/local/lib/python3.7/xml/etree/ElementPath.py", line 307, in find
    return next(iterfind(elem, path, namespaces), None)
TypeError: 'NoneType' object is not an iterator

**Comment by ksya** [comment]
Could you all try again?

**Comment by TomZegers** [comment]
Deleted the manual installed files and installed using HACS.
Rebooted 5 times, 3 of which were OK. 2 times a disconnect at boot.
This fix improved it very much!
I will have to wait if it disconnects at random but still... big improvement!

**Comment by Step-han** [comment]
I've did same test, 5 times reboot, 5 times are connected. Thanks for the update!
