### ISSUE TITLE
Error setting up entry <number> for nefiteasy since 2022.7.x

### ISSUE THREAD

**Issue by sanderlv** [ksya/ha-nefiteasy#162]
Hi, since updating to 2022.7.x (I think) this marvelous integration is not working anymore for me.

This is one of the i tegrations I am most proud of 😀. I use it in my holiday scenes, monitoring kids shower and other automation. Now it is suddenly "greyed out" 🥲.

Is there something wrong with it? Did I miss a breaking change?

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/nefiteasy/__init__.py:107
Integration: Nefit Easy Bosch Thermostat (documentation, issues)
First occurred: 11:40:12 (1 occurrences)
Last logged: 11:40:12

Error setting up entry <number> for nefiteasy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nefiteasy/__init__.py", line 44, in async_setup_entry
    client = NefitEasy(hass, credentials)
  File "/config/custom_components/nefiteasy/__init__.py", line 107, in __init__
    self.nefit = NefitCore(
  File "/usr/local/lib/python3.10/site-packages/aionefit/__init__.py", line 45, in __init__
    self.xmppclient = NefitXmppClient(jid=self.jid,
  File "/usr/local/lib/python3.10/site-packages/aionefit/provider/slixmpp_impl.py", line 32, in __init__
    self.register_plugin('xep_0280') #carbons
  File "/usr/local/lib/python3.10/site-packages/slixmpp/basexmpp.py", line 241, in register_plugin
    self.plugin.enable(plugin, pconfig)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 165, in enable
    self.enable(dep, enabled=enabled)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 165, in enable
    self.enable(dep, enabled=enabled)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 153, in enable
    load_plugin(name)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 82, in load_plugin
    __import__(module)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0203/__init__.py", line 11, in <module>
    from slixmpp.plugins.xep_0203 import stanza
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0203/stanza.py", line 13, in <module>
    from slixmpp.plugins import xep_0082
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0082.py", line 12, in <module>
    from slixmpp.thirdparty import tzutc, tzoffset, parse_iso
  File "/usr/local/lib/python3.10/site-packages/slixmpp/thirdparty/__init__.py", line 7, in <module>
    from slixmpp.thirdparty.orderedset import OrderedSet
  File "/usr/local/lib/python3.10/site-packages/slixmpp/thirdparty/orderedset.py", line 25, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

**Comment by RobBie1221** [comment]
Duplicate of #153

**Comment by sanderlv** [comment]
Sorry, see duplicate. But that seems to have stalled? Or is there any progress or resolution (to come).

Thank you

**Comment by RobBie1221** [comment]
See also #152 
Temporary fix is coming

**Comment by sanderlv** [comment]
Great thanks!!!

**Comment by sanderlv** [comment]
I think it is solved for me after going to v3 via hacs.

THANK YOU!
