### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableSet'

### ISSUE THREAD

**Issue by koos147** [ksya/ha-nefiteasy#181]
today i pulled the latest docker image (Home Assistant 2022.8.4 Frontend 20220802.0 - latest)
now my thermostat isn't working anymore.
any idea how we can fix this?

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/nefiteasy/__init__.py:169
Integration: Nefit Easy Bosch Thermostat (documentation, issues)
First occurred: 7:45:21 PM (1 occurrences)
Last logged: 7:45:21 PM

Error setting up entry 6******5 for nefiteasy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nefiteasy/__init__.py", line 106, in async_setup_entry
    client = NefitEasy(hass, credentials)
  File "/config/custom_components/nefiteasy/__init__.py", line 169, in __init__
    self.nefit = NefitCore(
  File "/usr/local/lib/python3.10/site-packages/aionefit/__init__.py", line 45, in __init__
    self.xmppclient = NefitXmppClient(jid=self.jid,
  File "/usr/local/lib/python3.10/site-packages/aionefit/provider/slixmpp_impl.py", line 32, in __init__
    self.register_plugin('xep_0280') #carbons
  File "/usr/local/lib/python3.10/site-packages/slixmpp/basexmpp.py", line 241, in register_plugin
    self.plugin.enable(plugin, pconfig)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 165, in enable
    self.enable(dep, enabled=enabled)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 165, in enable
    self.enable(dep, enabled=enabled)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 153, in enable
    load_plugin(name)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/base.py", line 82, in load_plugin
    __import__(module)
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0203/__init__.py", line 11, in <module>
    from slixmpp.plugins.xep_0203 import stanza
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0203/stanza.py", line 13, in <module>
    from slixmpp.plugins import xep_0082
  File "/usr/local/lib/python3.10/site-packages/slixmpp/plugins/xep_0082.py", line 12, in <module>
    from slixmpp.thirdparty import tzutc, tzoffset, parse_iso
  File "/usr/local/lib/python3.10/site-packages/slixmpp/thirdparty/__init__.py", line 7, in <module>
    from slixmpp.thirdparty.orderedset import OrderedSet
  File "/usr/local/lib/python3.10/site-packages/slixmpp/thirdparty/orderedset.py", line 25, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

```

**Comment by RobBie1221** [comment]
Update to the latest version of this integration.

**Comment by RobBie1221** [comment]
Latest version is 0.3.0
Are you using that one?

**Comment by koos147** [comment]
how can i see the intergration version?
can't find it anywhere (and google isn't helpful this time )

**Comment by RobBie1221** [comment]
It's in manifest.json.

Are you using HACS? If yes, this may be useful:
https://github.com/ksya/ha-nefiteasy/issues/152#issuecomment-1185836817

**Comment by koos147** [comment]
not yet, but will check it out right now

**Comment by RobBie1221** [comment]
So basically you downloaded from here and copied it to your HA?
That's not going to pick up updates...

**Comment by koos147** [comment]
that was something i did in the past. but it was replaced by the "add intergration" in the gui

**Comment by RobBie1221** [comment]
Add integration add's an instance of the integration to your configuration. It's not re-downloading sources from Github and copying it to your local HA filesystem.

**Comment by koos147** [comment]
aha, that makes sense, i was expecting the intergration followes the core while updating.
i installed HACS and let it download the intergration. now everythings works again. thanks for the support.
