### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by nanexception** [ksya/ha-nefiteasy#2]
Just installed a fresh version of HA(0.99.0) on Raspbian Lite, installing the component in the correct folder: /custom_components/nefiteasy/ and rebooting it gives an error notification in HA:
```
Invalid config
The following components and platforms could not be set up:
 - nefiteasy
Please check your config.

Nefit error
Timeout while connecting to Bosch cloud. Retrying in the background

```

configuration.yaml
```
nefiteasy:
  serial: 'hidden'
  accesskey: 'hidden'
  password: 'hidden'
  name: Nefit Easy #optional
  min_temp: 15 #optional
  max_temp: 27 #optional


logger:
  default: info
  logs:
    custom_components.nefiteasy: debug
    aionefit: debug
```

Log
```
2019-09-20 10:11:08 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2019-09-20 10:11:08 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 1.1 seconds.
2019-09-20 10:11:08 INFO (MainThread) [homeassistant.setup] Setup of domain device_tracker took 4.8 seconds.
2019-09-20 10:11:08 INFO (MainThread) [homeassistant.setup] Setting up default_config
2019-09-20 10:11:08 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.0 seconds.
2019-09-20 10:11:08 ERROR (MainThread) [homeassistant.core] Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1056)
2019-09-20 10:11:08 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error in data received
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1056)
2019-09-20 10:11:08 ERROR (MainThread) [slixmpp.xmlstream.xmlstream] CERT: Invalid certificate trust chain.
2019-09-20 10:11:10 WARNING (MainThread) [homeassistant.setup] Setup of nefiteasy is taking over 10 seconds.
2019-09-20 10:11:14 DEBUG (MainThread) [custom_components.nefiteasy] TimeoutError on waiting for connected event
2019-09-20 10:11:14 ERROR (MainThread) [homeassistant.setup] Error during setup of component nefiteasy
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nefiteasy/__init__.py", line 91, in connect
    await asyncio.wait_for(self.nefit.xmppclient.connected_event.wait(), timeout=15.0)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/home/homeassistant/.homeassistant/custom_components/nefiteasy/__init__.py", line 57, in async_setup
    await client.connect()
  File "/home/homeassistant/.homeassistant/custom_components/nefiteasy/__init__.py", line 101, in connect
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady
2019-09-20 10:11:19 INFO (SyncWorker_18) [homeassistant.components.nmap_tracker.device_tracker] No MAC address found for 192.168.178.24
2019-09-20 10:11:19 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 22.39s
2019-09-20 10:11:19 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2019-09-20 10:11:19 INFO (MainThread) [homeassistant.core] Timer:starting
```
It seems to be an SSL issue, is there any way to solving this?

**Comment by nanexception** [comment]
After googling a bit I've found this:
https://github.com/robertklep/nefit-easy-http-server/issues/35#issuecomment-510818042
With link to the source https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#openssl-defaults
