### ISSUE TITLE
Timeout fetching nefiteasy data

### ISSUE THREAD

**Issue by rsr-dev** [ksya/ha-nefiteasy#289]
Hi all,

i have the next issue. the nefit easy integration keeps getting thrown out
below the log file

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.nefiteasy
Source: helpers/update_coordinator.py:306
Integration: Nefit Easy Bosch Thermostat (documentation, issues)
First occurred: 5 januari 2024 om 22:44:12 (1 occurrences)
Last logged: 5 januari 2024 om 22:44:12

Timeout fetching nefiteasy data

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.nefiteasy
Source: helpers/update_coordinator.py:300
Integration: Nefit Easy Bosch Thermostat (documentation, issues)
First occurred: 5 januari 2024 om 22:46:21 (1 occurrences)
Last logged: 5 januari 2024 om 22:46:21

Unexpected error fetching nefiteasy data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nefiteasy/__init__.py", line 262, in _async_update_data
    await self.connect()
  File "/config/custom_components/nefiteasy/__init__.py", line 148, in connect
    self.nefit.get("/gateway/brandID")
  File "/usr/local/lib/python3.11/site-packages/aionefit/__init__.py", line 107, in get
    self.xmppclient.send_message(mto=self._to, mbody=msg)
  File "/usr/local/lib/python3.11/site-packages/aionefit/provider/slixmpp_impl.py", line 93, in send_message
    message.stream.send_raw(str_data)
  File "/usr/local/lib/python3.11/site-packages/slixmpp/xmlstream/xmlstream.py", line 1354, in send_raw
    raise NotConnectedError()
slixmpp.xmlstream.xmlstream.NotConnectedError

**Comment by AdeZwart** [comment]
Related to [271](https://github.com/ksya/ha-nefiteasy/issues/271)

I've captured some debug logs:
```
2024-01-08 13:44:16.995 ERROR (MainThread) [custom_components.nefiteasy] Unexpected error fetching nefiteasy data: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nefiteasy/__init__.py", line 262, in _async_update_data
    await self.connect()
  File "/config/custom_components/nefiteasy/__init__.py", line 148, in connect
    self.nefit.get("/gateway/brandID")
  File "/usr/local/lib/python3.11/site-packages/aionefit/__init__.py", line 107, in get
    self.xmppclient.send_message(mto=self._to, mbody=msg)
  File "/usr/local/lib/python3.11/site-packages/aionefit/provider/slixmpp_impl.py", line 93, in send_message
    message.stream.send_raw(str_data)
  File "/usr/local/lib/python3.11/site-packages/slixmpp/xmlstream/xmlstream.py", line 1354, in send_raw
    raise NotConnectedError()
slixmpp.xmlstream.xmlstream.NotConnectedError
2024-01-08 13:44:17.020 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.032 seconds (success: False)
2024-01-08 13:44:18.301 DEBUG (MainThread) [aionefit.provider.slixmpp_impl] auth_success event: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cnNwYXV0aD1kMWMyNjAwYWJmNzcwZjY1YTNmMTE4MTg5N2ViNjhjZA==</success>
2024-01-08 13:45:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Starting reconnect procedure.
2024-01-08 13:45:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Start connecting.
2024-01-08 13:45:16.990 DEBUG (MainThread) [custom_components.nefiteasy] Connection procedure is already running.
2024-01-08 13:45:16.990 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.002 seconds (success: False)
2024-01-08 13:46:16.988 DEBUG (MainThread) [custom_components.nefiteasy] Starting reconnect procedure.
2024-01-08 13:46:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Start connecting.
2024-01-08 13:46:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Connection procedure is already running.
2024-01-08 13:46:16.990 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.002 seconds (success: False)
2024-01-08 13:47:16.993 DEBUG (MainThread) [custom_components.nefiteasy] Starting reconnect procedure.
2024-01-08 13:47:16.994 DEBUG (MainThread) [custom_components.nefiteasy] Start connecting.
2024-01-08 13:47:16.994 DEBUG (MainThread) [custom_components.nefiteasy] Connection procedure is already running.
2024-01-08 13:47:16.995 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.002 seconds (success: False)
2024-01-08 13:48:16.988 DEBUG (MainThread) [custom_components.nefiteasy] Starting reconnect procedure.
2024-01-08 13:48:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Start connecting.
2024-01-08 13:48:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Connection procedure is already running.
2024-01-08 13:48:16.990 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.002 seconds (success: False)
2024-01-08 13:49:16.988 DEBUG (MainThread) [custom_components.nefiteasy] Starting reconnect procedure.
2024-01-08 13:49:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Start connecting.
2024-01-08 13:49:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Connection procedure is already running.
2024-01-08 13:49:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.001 seconds (success: False)
2024-01-08 13:50:16.988 DEBUG (MainThread) [custom_components.nefiteasy] Starting reconnect procedure.
2024-01-08 13:50:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Start connecting.
2024-01-08 13:50:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Connection procedure is already running.
2024-01-08 13:50:16.990 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.002 seconds (success: False)
2024-01-08 13:51:16.988 DEBUG (MainThread) [custom_components.nefiteasy] Starting reconnect procedure.
2024-01-08 13:51:16.988 DEBUG (MainThread) [custom_components.nefiteasy] Start connecting.
2024-01-08 13:51:16.988 DEBUG (MainThread) [custom_components.nefiteasy] Connection procedure is already running.
2024-01-08 13:51:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.001 seconds (success: False)
2024-01-08 13:52:16.988 DEBUG (MainThread) [custom_components.nefiteasy] Starting reconnect procedure.
2024-01-08 13:52:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Start connecting.
2024-01-08 13:52:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Connection procedure is already running.
2024-01-08 13:52:16.989 DEBUG (MainThread) [custom_components.nefiteasy] Finished fetching nefiteasy data in 0.001 seconds (success: False)
```

**Comment by sanderlv** [comment]
Same here... many of my automations rely on this integration (status of nefit) and the all stops...

reloading the integration always solves the issue:

This error originated from a custom integration.

Logger: custom_components.nefiteasy
Source: helpers/update_coordinator.py:306
Integration: Nefit Easy Bosch Thermostat (documentation, issues)
First occurred: 20:06:20 (1 occurrences)
Last logged: 20:06:20

Timeout fetching nefiteasy data

**Comment by RobBie1221** [comment]
Please try the newest version 0.4.1, this should be fixed. If not create a new issue with updated logs.
