### ISSUE TITLE
Connection drops - a lot

### ISSUE THREAD

**Issue by sanderlv** [ksya/ha-nefiteasy#318]
Is it just me, or does the connection drop a lot (becomes unavailable).

A while ago, the solution was to set an automation to reload the integration.

Recently, I discovered that "there was something solved" and the automation was not recommended anymore.

I rebuilt it to only see (get a notification) when it's unavailable. 

And it's a lot (!)

Today, starting at 0.00 it became unavailable for about 10 times...

![Screenshot_20240503_084001_Home Assistant.jpg](https://github.com/ksya/ha-nefiteasy/assets/16528916/cdd7fec9-f049-40d9-b055-3d24ebbab9a3)

![Uploading Screenshot_20240503_083954_Home Assistant.jpg …]()

com/ksya/ha-nefiteasy/assets/16528916/d257667e-b3c0-441a-9511-4821ab945878)

Is it just me? If it Nefit?

I need to know because a lot of my automations depend on this one (as a trigger).

Thanks in advance!!!

**Comment by RobBie1221** [comment]
It could be your WiFi connection. The Nefit server is also infamous for its instability. It was also not designed for this use. The app creates a connection and as soon as you browse away from the app the connection is dropped. This integration tries to keep a connection alive 24/7, which was never the intended use of the server.

The integration tries to make the best out of it, reconnecting until it is working again.

**Comment by sanderlv** [comment]
Hm... is it so that when my nefit easy itself disconnects it also is disconnected in HA?

I do see some dis- and reconnects on wifi yes... I have multiple APs.
It seems that 2 of them on channel "1" and on on "6"  get random connection requests form the nefit easy (same SSID). And nefit easy is the only client (of many) doing this...

Is that familiar?

**Comment by RobBie1221** [comment]
No not really. I don’t have a Nefit easy anymore. I had one and also had UniFi AP’s which provide very stable WiFi. I did have some disconnects but in the order of one or two per week. Not that much.

**Comment by sanderlv** [comment]
Hm... where did you go to (instead of nefit easy)?

**Comment by RobBie1221** [comment]
I moved to a new house. It has a complete installation from Itho (Heatpump, Autotemp, Spider).

**Comment by dhover** [comment]
I've the same experience with my Nefit Easy thermostat. The connection to the cloud drops often. Almost every day. The cause is the cloud server which looks not suited well.

**Comment by jeroen-vd-nl** [comment]
I also experienced this, and turned on debug info. It seems like (only) when reconnecting, data is received before the plugin expects this. As a result, the connection is not considered active. This does not happen when the plugin (re)loads the device and its entities in the way it doesn’t reconnect.

As a developer I tried to figure out the issue, but it wasn’t that easy (also because I am better in other languages). Because of that, as well as the finding that a reload works fine, I created a workaround: when Nefit is unavailable more than 3 minutes: reload nefit. To doublecheck I added a message to show the automation ran. It ran twice this week, got no more issues of a not connected Nefit when I wanted to use it.

'''
alias: Nefit reload bij unavailable
description: Workaround om Nefit beschikbaar te houden
trigger:
  - platform: state
    entity_id: climate.nefit
    to:
      - unknown
      - unavailable
    for:
      minutes: 3
action:
  - service: homeassistant.reload_config_entry
    target:
      device_id: b907ac7ba856b8e55db9afb7fc494526
    data: {}
  - service: notify.persistent_notification
    metadata: {}
    data:
      message: Nefit herstart
mode: single
'''

**Comment by dhutchison** [comment]
@jeroen-vd-nl would you be able to share the logs that lead you to that conclusion? I may try take a poke through the code to take a look, but no guarantees! (and thanks for the automation template, I was just about to write one when I came across this)

**Comment by dhover** [comment]
That is a really nice automation which seems to solve the connection problems.

**Comment by arjanvdnoort** [comment]
I also had a lot of "status became unavailable" messages. Since I moved my HA from Virtual Machine on NAS (DS220+) to Raspberry PI the problem seems to be gone.
Not the most easiest/cheap solution, but maybe it is helpfull for those looking for a solution

**Comment by sanderlv** [comment]
Hi all, I think many more problems on my side are worse since 17 november. It seems there was some maintenance according to the site of nefit.

I asked nefit for help (in Dutch)

Na meer dan 10 jaar probleemloze werking is er sinds 2 weken om de haverklap storing met mijn nefit easy icm easy connect adapter.
Op telefonisch advies heb ik alle 3 uitgezet. Daarna 1. Ketel aan, 2. Connect aan, 3. Easy aan.
Maar regelmatig is de easy opgelicht met 1 rood kruis. Raar want de connect is op dat moment groen en ik kan er via de app ook bij (?).
Na enig tijd lost het zich op en komen er 3 groene vinkjes.
Het is behoorlijk irritant...

Wat is hier aan de hand? Graag een echt antwoord en geen standaard "doe alles even uit en aan" antwoord. Het probleem is omstreeks 17 novemer ontstaan.

**Comment by jeroen-vd-nl** [comment]
My thoughts: Nefit/Bosch will not support this thermostat much, as Bosh has a new home system. My workaround still helps, but problem indeed stays. I do run on a Pi, having HAOS as the only thing running, so @arjanvdnoort I guess you’re lucky it helps for you. Since I’m improving my house with a home battery and a waterpump heater I decided to also update my thermostat and it won’t be a Bosch/Nefit.

**Comment by ChefkeGremmen** [comment]
I recognize the periods of bad connection, but the last couple of weeks its ok at my house.
For other solutions; I have been wanting the [EMS Gateway from BBQKees](https://bbqkees-electronics.nl/shop/?lang=nl) for a while now. But besides the once in a while connection errors, the custom component still serves me well (enough).

**Comment by BrainDra1n** [comment]
I observed the same behavior as @jeroen-vd-nl :

> I also experienced this, and turned on debug info. It seems like (only) when reconnecting, data is received before the plugin expects this. As a result, the connection is not considered active. This does not happen when the plugin (re)loads the device and its entities in the way it doesn’t reconnect.

Reloading the Integration solved this. So this bug is still present. This is what I found in the HA logs:

It starts with this once:
```
2025-02-14 04:05:17.419 ERROR (MainThread) [custom_components.nefiteasy] Error fetching nefiteasy data: Nefit easy not connected!
```
Then repeats many times:
```
2025-02-14 05:14:08.874 ERROR (MainThread) [slixmpp.basexmpp] There is already a scheduled event of name: Whitespace Keepalive
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/slixmpp/xmlstream/xmlstream.py", line 1106, in event
    handler_callback(data)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/slixmpp/xmlstream/xmlstream.py", line 860, in _start_keepalive
    self.schedule('Whitespace Keepalive',
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
                  self.whitespace_keepalive_interval,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  self.send_raw,
                  ^^^^^^^^^^^^^^
                  args=(' ',),
                  ^^^^^^^^^^^^
                  repeat=True)
                  ^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/slixmpp/xmlstream/xmlstream.py", line 1136, in schedule
    raise ValueError(
        "There is already a scheduled event of name: %s" % name)
ValueError: There is already a scheduled event of name: Whitespace Keepalive

```

Then after some time (45min), this changes to:
```
2025-02-14 06:00:36.823 WARNING (MainThread) [slixmpp.xmlstream.xmlstream] Received data before the connection is established: b'<iq type="get" id="149-1337523" from="wa2-mz36-qrmzh6.bosch.de" to="rrccontact_760920358@wa2-mz36-qrmzh6.bosch.de/5lflipnl5y"><ping xmlns="urn:xmpp:ping"/></iq>'
2025-02-14 06:05:33.910 ERROR (MainThread) [slixmpp.features.feature_starttls.stanza] Error handling {jabber:client}proceed stanza
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/slixmpp/xmlstream/handler/coroutine_callback.py", line 60, in pointer_wrapper
    await pointer(stanza)
  File "/usr/local/lib/python3.13/site-packages/slixmpp/features/feature_starttls/starttls.py", line 63, in _handle_starttls_proceed
    if await self.xmpp.start_tls():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/slixmpp/xmlstream/xmlstream.py", line 840, in start_tls
    der_cert = transp.get_extra_info("ssl_object").getpeercert(True)
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_extra_info'

```
Which seems to happen when the nefit connection is re-established.
When I subsequently reload the Integration, its works fine again.

The log does not show a 'disconnect' and 'connect'. So maybe the Integration does not flush its input buffer when disconnected. When connection is established again, the input buffer still contains some old stuff. So maybe this buffer needs to be cleared upon a disconnect. I have not looked at the source code. So I'm just guessing.

The problem is that he Integration never recovers from this state. So human intervention is necessary to correct this state. This is unwanted behaviour.

**Comment by BrainDra1n** [comment]
Today (monday 03-03-2025) it is especially bad. Had connection drop 9 times in 14 hours.
Is this the same for others?

If only I have this many connection drops, the problem is in on my end. If others experience this as well, it is caused by something we share. Like the Nefit backend.

**Comment by dhover** [comment]
I had also many drops. Integration not available, etc. I think the problems lay in the Nefit/Bosch backend. It is very unreliable!

**Comment by glazenborg** [comment]
Chatgpt tells me the slixmpp that Bosch is using is outdated. I had a whole range of these messages in HA: "2025-09-23 07:14:19.280 ERROR (MainThread) [custom_components.nefiteasy] Error fetching nefiteasy data: Nefit easy not connected!"

Now I am trying the same automation, hope it'll work.

**Comment by RobBie1221** [comment]
Fixed with #447
