### ISSUE TITLE
 Kan service climate/set_temperature niet aanroepen

### ISSUE THREAD

**Issue by gjvetten** [ksya/ha-nefiteasy#6]
Hello, I hope you can help me. I've update HA to the latest version (Hassio via Docker) version 0.101.2, All entities are available but I cannot set temperature.service climate/set_temperature error. Did I miss something. Thanks for helping out.

**Comment by ksya** [comment]
Please send the full contents of the error.

**Comment by gjvetten** [comment]
Hello,

Thanks for helping out. Here's the log. Is this what you are looking for?

2019-11-02 14:10:01 DEBUG (MainThread)
[custom_components.nefiteasy.nefit_device] async_update called for
supply_temperature
2019-11-02 14:10:01 DEBUG (MainThread) [aionefit] Sending msg...GET
/heatingCircuits/hc1/actualSupplyTemperature HTTP/1.1\rUser-Agent:
NefitEasy\r\r
2019-11-02 14:10:01 ERROR (MainThread) [homeassistant.helpers.entity]
Update for sensor.nefit_supply_temperature fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270,
in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448,
in async_device_update
    await self.async_update()
  File "/config/custom_components/nefiteasy/nefit_device.py", line 58, in
async_update
    self._client.nefit.get(self.get_endpoint())
  File "/usr/local/lib/python3.7/site-packages/aionefit/__init__.py", line
98, in get
    self.xmppclient.send_message(mto=self._to, mbody=msg)
  File
"/usr/local/lib/python3.7/site-packages/aionefit/provider/slixmpp_impl.py",
line 95, in send_message
  File
"/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py",
line 926, in send_raw
    raise NotConnectedError()
slixmpp.xmlstream.xmlstream.NotConnectedError
2019-11-02 14:10:01 DEBUG (MainThread)
[custom_components.nefiteasy.nefit_device] async_update called for
hot_water_operation
2019-11-02 14:10:01 DEBUG (MainThread) [aionefit] Sending msg...GET
/dhwCircuits/dhwA/dhwOperationType HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-11-02 14:10:01 ERROR (MainThread) [homeassistant.helpers.entity]
Update for sensor.nefit_hot_water_operation fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270,
in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448,
in async_device_update
    await self.async_update()
  File "/config/custom_components/nefiteasy/nefit_device.py", line 58, in
async_update
    self._client.nefit.get(self.get_endpoint())
  File "/usr/local/lib/python3.7/site-packages/aionefit/__init__.py", line
98, in get
    self.xmppclient.send_message(mto=self._to, mbody=msg)
  File
"/usr/local/lib/python3.7/site-packages/aionefit/provider/slixmpp_impl.py",
line 95, in send_message
  File
"/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py",
line 926, in send_raw
    raise NotConnectedError()
slixmpp.xmlstream.xmlstream.NotConnectedError
2019-11-02 14:10:01 DEBUG (MainThread)
[custom_components.nefiteasy.nefit_device] async_update called for status
2019-11-02 14:10:01 DEBUG (MainThread) [aionefit] Sending msg...GET
/system/appliance/displaycode HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-11-02 14:10:01 ERROR (MainThread) [homeassistant.helpers.entity]
Update for sensor.nefit_status fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270,
in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448,
in async_device_update
    await self.async_update()
  File "/config/custom_components/nefiteasy/nefit_device.py", line 58, in
async_update
    self._client.nefit.get(self.get_endpoint())
  File "/usr/local/lib/python3.7/site-packages/aionefit/__init__.py", line
98, in get
    self.xmppclient.send_message(mto=self._to, mbody=msg)
  File
"/usr/local/lib/python3.7/site-packages/aionefit/provider/slixmpp_impl.py",
line 95, in send_message
  File
"/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py",
line 926, in send_raw
    raise NotConnectedError()
slixmpp.xmlstream.xmlstream.NotConnectedError
2019-11-02 14:10:08 ERROR (MainThread)
[homeassistant.components.websocket_api.http.connection.140516932499984]
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py",
line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1236, in
async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in
_execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py",
line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 348,
in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 370,
in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File
"/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line
415, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in
run
    result = self.fn(*self.args, **self.kwargs)
  File
"/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line
411, in set_hvac_mode
    raise NotImplementedError()
NotImplementedError

GJ

Op za 2 nov. 2019 om 12:12 schreef ksya <notifications@github.com>:

**Comment by ksya** [comment]
Please reinstall the plugin. There is no line 411 in __init__.py, which might indicate you are using older files or didn't overwrite some other version.

**Comment by gjvetten** [comment]
Hello,

Line 411? The file on GitHub is attached. 165 lines.
Thanks.

GJ

Op za 2 nov. 2019 om 14:24 schreef ksya <notifications@github.com>:

**Comment by ksya** [comment]
Yes sorry, will check later. I already deleted my comment :)

**Comment by ksya** [comment]
Is this with the current Github version/latest commit?
I see you have "NotConnectedError", which I hoped to have fixed in the latest commit.

**Comment by gjvetten** [comment]
Yes, taken from https://github.com/ksya/ha-nefiteasy. Unfortunately I do
receive timeouts as well (Timeout while connecting to Bosch cloud. Retrying
in the background).

Op za 2 nov. 2019 om 17:55 schreef ksya <notifications@github.com>:

**Comment by yellowonblack** [comment]
Using the last version of the component and last version of HA 0.102.3 (as Docker container), the component freezes at random times (sometimes hours and sometimes days after HA restart) with the below error.

2019-12-11 18:02:36 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.nefit_status fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/nefiteasy/nefit_device.py", line 58, in async_update
    self._client.nefit.get(self.get_endpoint())
  File "/usr/local/lib/python3.7/site-packages/aionefit/__init__.py", line 98, in get
    self.xmppclient.send_message(mto=self._to, mbody=msg)
  File "/usr/local/lib/python3.7/site-packages/aionefit/provider/slixmpp_impl.py", line 95, in send_message
    message.stream.send_raw(str_data)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 926, in send_raw
    raise NotConnectedError()
slixmpp.xmlstream.xmlstream.NotConnectedError

**Comment by ksya** [comment]
I don't think this is still relevant. Otherwise, please respond here or open new issue.

**Comment by gjvetten** [comment]
Hello Ksya,

I've installed the latest updates. Unfortunately same errors - issues.

Unexpected disconnect of 517910036 with Bosch server
Timeout while connecting 517910036 to Bosch cloud

GJ

Op za 25 jan. 2020 om 12:15 schreef ksya <notifications@github.com>:
