### ISSUE TITLE
Error from HA after update from HA i think

### ISSUE THREAD

**Issue by Willy3D** [ksya/ha-nefiteasy#63]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/nefiteasy/__init__.py:169
Integration: Nefit Easy Bosch Thermostat (documentation, issues)
First occurred: 20:09:03 (1 occurrences)
Last logged: 20:09:03

Error setting up entry 519 911 274 for nefiteasy
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/slixmpp/stringprep.py", line 55, in nodeprep
    return _nodeprep(node)
  File "/usr/local/lib/python3.8/site-packages/slixmpp/util/stringprep_profiles.py", line 145, in profile
    prohibit_output(data, prohibited)
  File "/usr/local/lib/python3.8/site-packages/slixmpp/util/stringprep_profiles.py", line 78, in prohibit_output
    raise StringPrepError("Prohibited code point: %s" % char)
slixmpp.util.stringprep_profiles.StringPrepError: Prohibited code point:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 86, in _validate_node
    node = nodeprep(node)
  File "/usr/local/lib/python3.8/site-packages/slixmpp/stringprep.py", line 57, in nodeprep
    raise StringprepError
slixmpp.stringprep.StringprepError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/nefiteasy/__init__.py", line 106, in async_setup_entry
    client = NefitEasy(hass, credentials)
  File "/config/custom_components/nefiteasy/__init__.py", line 169, in __init__
    self.nefit = NefitCore(
  File "/usr/local/lib/python3.8/site-packages/aionefit/__init__.py", line 45, in __init__
    self.xmppclient = NefitXmppClient(jid=self.jid,
  File "/usr/local/lib/python3.8/site-packages/aionefit/provider/slixmpp_impl.py", line 15, in __init__
    slixmpp.ClientXMPP.__init__(self, jid, password,
  File "/usr/local/lib/python3.8/site-packages/slixmpp/clientxmpp.py", line 70, in __init__
    BaseXMPP.__init__(self, jid, 'jabber:client', **kwargs)
  File "/usr/local/lib/python3.8/site-packages/slixmpp/basexmpp.py", line 58, in __init__
    self.requested_jid = JID(jid)
  File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 323, in __init__
    self._node, self._domain, self._resource = _parse_jid(jid)
  File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 68, in _parse_jid
    node = _validate_node(node)
  File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 88, in _validate_node
    raise InvalidJID('Nodeprep failed')
slixmpp.jid.InvalidJID: Nodeprep failed

**Comment by grmblmmmbl** [comment]
I have this exact same issue (new to HA so I was wondering if it's me!). I'm really interested in debussing / resolving this.

**Comment by RobBie1221** [comment]
Could this be the same as #57

**Comment by grmblmmmbl** [comment]
@RobBie1221 thank you! Following the instructions there (basically, check that your config is entered without spaces) certainly did the trick for me! @Willy3D FYI

**Comment by WillyWemos** [comment]
That thit the trick thanx !!!
