### ISSUE TITLE
Slixmmp errors

### ISSUE THREAD

**Issue by robvangeloven** [ksya/ha-nefiteasy#68]
Hi,

I've tried setting up the component, I'm getting this error now however:

```
2021-06-29 21:52:06 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2021-06-29 21:52:06 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 717 912 766 for nefiteasy
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/slixmpp/stringprep.py", line 55, in nodeprep
return _nodeprep(node)
File "/usr/local/lib/python3.8/site-packages/slixmpp/util/stringprep_profiles.py", line 145, in profile
prohibit_output(data, prohibited)
File "/usr/local/lib/python3.8/site-packages/slixmpp/util/stringprep_profiles.py", line 78, in prohibit_output
raise StringPrepError("Prohibited code point: %s" % char)
slixmpp.util.stringprep_profiles.StringPrepError: Prohibited code point:
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 86, in _validate_node
node = nodeprep(node)
File "/usr/local/lib/python3.8/site-packages/slixmpp/stringprep.py", line 57, in nodeprep
raise StringprepError
slixmpp.stringprep.StringprepError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/nefiteasy/__init__.py", line 106, in async_setup_entry
client = NefitEasy(hass, credentials)
File "/config/custom_components/nefiteasy/__init__.py", line 169, in __init__
self.nefit = NefitCore(
File "/usr/local/lib/python3.8/site-packages/aionefit/__init__.py", line 45, in __init__
self.xmppclient = NefitXmppClient(jid=self.jid,
File "/usr/local/lib/python3.8/site-packages/aionefit/provider/slixmpp_impl.py", line 15, in __init__
slixmpp.ClientXMPP.__init__(self, jid, password,
File "/usr/local/lib/python3.8/site-packages/slixmpp/clientxmpp.py", line 70, in __init__
BaseXMPP.__init__(self, jid, 'jabber:client', **kwargs)
File "/usr/local/lib/python3.8/site-packages/slixmpp/basexmpp.py", line 58, in __init__
self.requested_jid = JID(jid)
File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 323, in __init__
self._node, self._domain, self._resource = _parse_jid(jid)
File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 68, in _parse_jid
node = _validate_node(node)
File "/usr/local/lib/python3.8/site-packages/slixmpp/jid.py", line 88, in _validate_node
raise InvalidJID('Nodeprep failed')
slixmpp.jid.InvalidJID: Nodeprep failed
```

**Comment by RobBie1221** [comment]
Same as #57 ?

**Comment by robvangeloven** [comment]
> Same as #57 ?

Yup. And I thought I did a good search  :(
