### ISSUE TITLE
Error when starting Nefit Easy phone app

### ISSUE THREAD

**Issue by harryd100** [ksya/ha-nefiteasy#8]
When the integration is running and I open the phone app, the following errors occur in the HA log

2019-11-27 20:48:21 ERROR (MainThread) [slixmpp.stanza.rootstanza] Error handling {jabber:client}message stanza
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aionefit/provider/pyaes_impl.py", line 35, in decrypt
    r = decrypted.decode("utf8").rstrip(chr(0))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 796, in event
    handler_callback(data)
  File "/usr/local/lib/python3.7/site-packages/aionefit/provider/slixmpp_impl.py", line 76, in carbonmsg_recv_callblack
    self.nefit_client.raw_message_callback(msg['carbon_received'])
  File "/usr/local/lib/python3.7/site-packages/aionefit/__init__.py", line 63, in raw_message_callback
    response = self.encryption.decrypt(body)
  File "/usr/local/lib/python3.7/site-packages/aionefit/provider/pyaes_impl.py", line 37, in decrypt
    raise SystemError("Decryption error (%s). Wrong password?", e)
SystemError: ('Decryption error (%s). Wrong password?', UnicodeDecodeError('utf-8', b'\rx\xb9\xdeV0@]\xbeW#\xfe\x81"=*\x99\x17\xbd\xd4p\xcb\xb5\x8f\xd41\xf6K\xab\xec\xff\xe3k\xce\xa6\xd3\xc03#\xce_\x1e$\xbdo\n\x8c\xc8j;\xc0\xce\\j\xe3\xb6\xbfz\x070AN:\x81"\xe0\xfd\xb5\x0b\xb5\x08\xfb\x85Z\xdc\xb6E\xb2{\x03_na\x02\\\xb4G\x02B\xd9\x97\x06\xc3\xc4\x88\xfbR\xa8\xe6\x05;\xc6$\xc2\xe0\xf9w@\x81\xcb\xf6=', 2, 3, 'invalid start byte'))
2019-11-27 20:48:21 ERROR (MainThread) [slixmpp.basexmpp] ('Decryption error (%s). Wrong password?', UnicodeDecodeError('utf-8', b'\rx\xb9\xdeV0@]\xbeW#\xfe\x81"=*\x99\x17\xbd\xd4p\xcb\xb5\x8f\xd41\xf6K\xab\xec\xff\xe3k\xce\xa6\xd3\xc03#\xce_\x1e$\xbdo\n\x8c\xc8j;\xc0\xce\\j\xe3\xb6\xbfz\x070AN:\x81"\xe0\xfd\xb5\x0b\xb5\x08\xfb\x85Z\xdc\xb6E\xb2{\x03_na\x02\\\xb4G\x02B\xd9\x97\x06\xc3\xc4\x88\xfbR\xa8\xe6\x05;\xc6$\xc2\xe0\xf9w@\x81\xcb\xf6=', 2, 3, 'invalid start byte'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aionefit/provider/pyaes_impl.py", line 35, in decrypt
    r = decrypted.decode("utf8").rstrip(chr(0))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 796, in event
    handler_callback(data)
  File "/usr/local/lib/python3.7/site-packages/aionefit/provider/slixmpp_impl.py", line 76, in carbonmsg_recv_callblack
    self.nefit_client.raw_message_callback(msg['carbon_received'])
  File "/usr/local/lib/python3.7/site-packages/aionefit/__init__.py", line 63, in raw_message_callback
    response = self.encryption.decrypt(body)
  File "/usr/local/lib/python3.7/site-packages/aionefit/provider/pyaes_impl.py", line 37, in decrypt
    raise SystemError("Decryption error (%s). Wrong password?", e)
SystemError: ('Decryption error (%s). Wrong password?', UnicodeDecodeError('utf-8', b'\rx\xb9\xdeV0@]\xbeW#\xfe\x81"=*\x99\x17\xbd\xd4p\xcb\xb5\x8f\xd41\xf6K\xab\xec\xff\xe3k\xce\xa6\xd3\xc03#\xce_\x1e$\xbdo\n\x8c\xc8j;\xc0\xce\\j\xe3\xb6\xbfz\x070AN:\x81"\xe0\xfd\xb5\x0b\xb5\x08\xfb\x85Z\xdc\xb6E\xb2{\x03_na\x02\\\xb4G\x02B\xd9\x97\x06\xc3\xc4\x88\xfbR\xa8\xe6\x05;\xc6$\xc2\xe0\xf9w@\x81\xcb\xf6=', 2, 3, 'invalid start byte'))

Any idea where this is coming from? It looks like the integration is working however

**Comment by ksya** [comment]
Yes I have seen this as well some times. I am not sure what this is, but it doesn't harm anyone luckily.

**Comment by ksya** [comment]
These errors are now suppressed, since they are not relevant.
