### ISSUE TITLE
error setting up entry

### ISSUE THREAD

**Issue by AntoineMeurs** [ksya/ha-nefiteasy#84]
hi guys,

I receive an error installing my refit easy, after using the script I receive an error setting up entry in home assistants my integrations. underneath is a log which I can't get figured out.
Hopefully one of you guys can.

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/nefiteasy/__init__.py:171
Integration: Nefit Easy Bosch Thermostat (documentation, issues)
First occurred: 17:58:07 (1 occurrences)
Last logged: 17:58:07

Error setting up entry 757 920 478 for nefiteasy
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slixmpp/stringprep.py", line 55, in nodeprep
    return _nodeprep(node)
  File "/usr/local/lib/python3.9/site-packages/slixmpp/util/stringprep_profiles.py", line 145, in profile
    prohibit_output(data, prohibited)
  File "/usr/local/lib/python3.9/site-packages/slixmpp/util/stringprep_profiles.py", line 78, in prohibit_output
    raise StringPrepError("Prohibited code point: %s" % char)
slixmpp.util.stringprep_profiles.StringPrepError: Prohibited code point:  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slixmpp/jid.py", line 86, in _validate_node
    node = nodeprep(node)
  File "/usr/local/lib/python3.9/site-packages/slixmpp/stringprep.py", line 57, in nodeprep
    raise StringprepError
slixmpp.stringprep.StringprepError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/nefiteasy/__init__.py", line 108, in async_setup_entry
    client = NefitEasy(hass, credentials)
  File "/config/custom_components/nefiteasy/__init__.py", line 171, in __init__
    self.nefit = NefitCore(
  File "/usr/local/lib/python3.9/site-packages/aionefit/__init__.py", line 45, in __init__
    self.xmppclient = NefitXmppClient(jid=self.jid,
  File "/usr/local/lib/python3.9/site-packages/aionefit/provider/slixmpp_impl.py", line 15, in __init__
    slixmpp.ClientXMPP.__init__(self, jid, password,
  File "/usr/local/lib/python3.9/site-packages/slixmpp/clientxmpp.py", line 70, in __init__
    BaseXMPP.__init__(self, jid, 'jabber:client', **kwargs)
  File "/usr/local/lib/python3.9/site-packages/slixmpp/basexmpp.py", line 58, in __init__
    self.requested_jid = JID(jid)
  File "/usr/local/lib/python3.9/site-packages/slixmpp/jid.py", line 323, in __init__
    self._node, self._domain, self._resource = _parse_jid(jid)
  File "/usr/local/lib/python3.9/site-packages/slixmpp/jid.py", line 68, in _parse_jid
    node = _validate_node(node)
  File "/usr/local/lib/python3.9/site-packages/slixmpp/jid.py", line 88, in _validate_node
    raise InvalidJID('Nodeprep failed')
slixmpp.jid.InvalidJID: Nodeprep failed

**Comment by RobBie1221** [comment]
Same as #57 ?

**Comment by RobBie1221** [comment]
I assume you were able to solve it given the lack of response.
