### ISSUE TITLE
Multiple Connection Errors 

### ISSUE THREAD

**Issue by rickvanelk** [ksya/ha-nefiteasy#91]
Hi, 

I'm new with Home Assistant and tried to setup the Nefit Easy integration.
Home Assistant is running on Ubuntu 18.04.5 LTS using docker. 

I added following to configuration.yaml 
```
logger:
  default: info
  logs:
    custom_components.nefiteasy: debug
    aionefit: debug
```

When setting up the Nefit Integration, the screen will be in an endless loop, following errors are logged: 

```
Nefit connect error
Did not succeed in connecting 720962449 to Bosch cloud after retrying 3 times. Retry in 30 seconds.

No connection while testing connection.
11:52:49 PM – (ERROR) Nefit Easy Bosch Thermostat (custom integration) - message first occurred at 11:52:19 PM and shows up 2 times
Did not get a response in time for testing connection (validation retries=0).
11:52:19 PM – (ERROR) Nefit Easy Bosch Thermostat (custom integration)
Error handling {urn:ietf:params:xml:ns:xmpp-sasl}failure stanza
11:51:50 PM – (ERROR) Nefit Easy Bosch Thermostat (custom integration)
No appropriate login method.
11:51:50 PM – (ERROR) /usr/local/lib/python3.9/site-packages/slixmpp/features/feature_mechanisms/mechanisms.py
Error doing job: Task was destroyed but it is pending!
11:51:16 PM – (ERROR) runner.py
```

Home Assistant version: 
## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.4.0-91-generic
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4917
Installed Version | 1.18.0
Stage | running
Available Repositories | 909
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

I did try to set the openSSL configuration as mentioned for both the docker image and ubuntu host, but no success.

**Comment by rickvanelk** [comment]
After some further digging into the log trace, found following: 

```
2021-12-11 23:51:50 INFO (MainThread) [homeassistant.setup] Setting up nefiteasy
2021-12-11 23:51:50 INFO (MainThread) [homeassistant.setup] Setup of domain nefiteasy took 0.0 seconds
2021-12-11 23:51:50 DEBUG (MainThread) [custom_components.nefiteasy] Initialize Nefit class
2021-12-11 23:51:50 DEBUG (MainThread) [aionefit] Initializing XMPP client
2021-12-11 23:51:50 DEBUG (MainThread) [custom_components.nefiteasy] Starting connecting..
2021-12-11 23:51:50 DEBUG (MainThread) [custom_components.nefiteasy] Waiting for connected event
2021-12-11 23:51:50 INFO (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] Authentication failed: not-authorized
2021-12-11 23:51:50 ERROR (MainThread) [slixmpp.features.feature_mechanisms.mechanisms] No appropriate login method.
2021-12-11 23:51:50 DEBUG (MainThread) [custom_components.nefiteasy] Shutdown connection to Bosch cloud
2021-12-11 23:51:50 ERROR (MainThread) [slixmpp.xmlstream.stanzabase] Error handling {urn:ietf:params:xml:ns:xmpp-sasl}failure stanza
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 834, in handler_callback_routine
await cb(data)
File "/usr/local/lib/python3.9/site-packages/aionefit/provider/slixmpp_impl.py", line 55, in on_failed_auth
await self.nefit_client.failed_auth_handler(event)
File "/config/custom_components/nefiteasy/__init__.py", line 239, in failed_auth_handler
await self.shutdown("auth_failed")
File "/config/custom_components/nefiteasy/__init__.py", line 227, in shutdown
await self.nefit.disconnect()
File "/usr/local/lib/python3.9/site-packages/aionefit/__init__.py", line 55, in disconnect
self.xmppclient.disconnect()
File "/usr/local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 504, in disconnect
self.schedule('Disconnect wait', wait,
File "/usr/local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 875, in schedule
raise ValueError(
ValueError: There is already a scheduled event of name: Disconnect wait
2021-12-11 23:51:50 DEBUG (MainThread) [custom_components.nefiteasy] adding stop listener
2021-12-11 23:51:50 INFO (MainThread) [custom_components.nefiteasy] Testing connection (connect retries=0)
2021-12-11 23:51:50 DEBUG (MainThread) [aionefit] Sending msg...GET /gateway/brandID HTTP/1.1\rUser-Agent: NefitEasy\r\r
2021-12-11 23:51:51 INFO (MainThread) [slixmpp.xmlstream.xmlstream] connection_lost: (None,)
2021-12-11 23:51:51 DEBUG (MainThread) [aionefit.provider.slixmpp_impl] Connection was closed
2021-12-11 23:52:19 ERROR (MainThread) [custom_components.nefiteasy] Did not get a response in time for testing connection (validation retries=0).
```

**Comment by rickvanelk** [comment]
After a clean installation of Home Assistant it's working suddenly.
